### ISSUE TITLE
Shitcharts in Notifiarr installation guide image

### ISSUE THREAD

**Issue by brokenmass** [Heavybullets8/HeavySetup#8]
<img width="656" alt="image" src="https://github.com/Heavybullets8/HeavySetup/assets/1800988/3270027c-1df0-4804-9b13-3640df8c116a">

**Comment by Heavybullets8** [comment]
Fixed, thanks.
[#](https://github.com/Heavybullets8/HeavySetup/commit/3e2670d56d23ae1ef961433fba96c9f85fa33269)
